technologies = ['html', 
                'css', 
                'javascript', 
                'js', 
                'python', 
                'php', 
                'sql', 
                'c', 
                'c++', 
                'selenium', 
                'data sturctures',
                'linux']

topics = ['security', 
          'health', 
          'health care', 
          'education', 
          'educatinal purpose', 
          'web', 
          'web scraping', 
          'database']