my_technologies = ['html', 
                'css', 
                'javascript', 
                'js', 
                'python', 
                'php', 
                'sql', 
                'c', 
                'c++', 
                'selenium', 
                'data sturctures',
                'linux']

my_topics = ['security', 
            'health', 
            'health care', 
            'education', 
            'educatinal purpose', 
            'web', 
            'web scraping', 
            'database']

header = ["Org No", 
        "Name", 
        "Desc", 
        "Url", 
        "Technologies", 
        "Topics", 
        "My Score", 
        "Org Score", 
        "Org link", 
        "Guidance link"]
